on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: ${{ secrets.GCP_INSTANCE_NAME }}
        zone: 'us-west-1b'
        ssh_private_key: ${{ secrets.GCP_SSH_KEY }}
        command: |
          NAME=$(echo ${{ github.repository }} | sed -e 's#.*/##')
          docker rm $NAME
          docker run --name $NAME --env-file /var/bots/$NAME.env ghcr.io/${{ github.repository }}:latest

